# Periphery Configuration for Heauton
# Detects unused code in the project

workspace: Heauton/Heauton.xcodeproj
schemes:
  - Heauton

targets:
  - Heauton

# Exclude test files from unused code detection
skip_build: false
clean_build: true

# Retain certain declarations that may appear unused
retain_public: true
retain_objc_accessible: true
retain_objc_annotated: true

# External protocols that may appear unused but are used by SwiftUI/SwiftData
retain_codable_properties: true

# Custom retain patterns
retain_assign_only_properties: false

# Scan configuration
index_store_path: .build/index/store
report_exclude:
  - "**/Tests/**"
  - "**/Preview Content/**"
  - "**/*.generated.swift"
  - "**/DerivedData/**"

# Output format
format: xcode

# Disable certain checks for SwiftUI/SwiftData patterns
disable_unused_import_analysis: false
