# SwiftLint Configuration
# Exclude specific directories from linting
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - .swiftpm
  - HeautonTests
  - HeautonUITests

# Paths to include for linting
included:
  - Heauton

# Configure specific rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo
  - trailing_comma

# Rule configurations
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 5
    error: 7

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - URL
    - URI
    - i
    - j
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID

large_tuple:
  warning: 3
  error: 4

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 1

# Custom rules
custom_rules:
  no_print:
    name: "Print Usage"
    regex: "print\\("
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning

# Reporter type
reporter: "xcode"
